Explicitly add `netty-transport-native-unix-common` for Play 2.7
```
[info] be.venneborg.refined.play.SIRDServerSuite *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: io/netty/channel/unix/UnixChannelOption
[info]   at play.core.server.NettyServer.initializeChannelOptionsStaticMembers(NettyServer.scala:314)
[info]   at play.core.server.NettyServer.<init>(NettyServer.scala:63)
[info]   at play.core.server.NettyServerComponents.server(NettyServer.scala:405)
[info]   at play.core.server.NettyServerComponents.server$(NettyServer.scala:401)
[info]   at play.core.server.NettyServer$$anon$1.server$lzycompute(NettyServer.scala:390)
[info]   at play.core.server.NettyServer$$anon$1.server(NettyServer.scala:390)
[info]   at play.core.server.NettyServer$.createServerFromRouter(NettyServer.scala:390)
[info]   at play.core.server.ServerFromRouter.fromRouterWithComponents(Server.scala:315)
[info]   at play.core.server.ServerFromRouter.fromRouterWithComponents$(Server.scala:312)
[info]   at play.core.server.NettyServer$.fromRouterWithComponents(NettyServer.scala:361)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: io.netty.channel.unix.UnixChannelOption
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at play.core.server.NettyServer.initializeChannelOptionsStaticMembers(NettyServer.scala:314)
[info]   at play.core.server.NettyServer.<init>(NettyServer.scala:63)
[info]   at play.core.server.NettyServerComponents.server(NettyServer.scala:405)
[info]   at play.core.server.NettyServerComponents.server$(NettyServer.scala:401)
[info]   at play.core.server.NettyServer$$anon$1.server$lzycompute(NettyServer.scala:390)
[info]   at play.core.server.NettyServer$$anon$1.server(NettyServer.scala:390)
[info]   at play.core.server.NettyServer$.createServerFromRouter(NettyServer.scala:390)
[info]   ...
```