Update/refined 0.9.8 (#55)
* Update refined to 0.9.8

* travis: Update to Scala 2.13.0

* Upgrade Play to 2.7.3 and Play-Json to 2.7.4

* Upgrade Play WS standalone JSON to 2.0.6

* Explicitly add `netty-transport-native-unix-common` for Play 2.7

```
[info] be.venneborg.refined.play.SIRDServerSuite *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: io/netty/channel/unix/UnixChannelOption
[info]   at play.core.server.NettyServer.initializeChannelOptionsStaticMembers(NettyServer.scala:314)
[info]   at play.core.server.NettyServer.<init>(NettyServer.scala:63)
[info]   at play.core.server.NettyServerComponents.server(NettyServer.scala:405)
[info]   at play.core.server.NettyServerComponents.server$(NettyServer.scala:401)
[info]   at play.core.server.NettyServer$$anon$1.server$lzycompute(NettyServer.scala:390)
[info]   at play.core.server.NettyServer$$anon$1.server(NettyServer.scala:390)
[info]   at play.core.server.NettyServer$.createServerFromRouter(NettyServer.scala:390)
[info]   at play.core.server.ServerFromRouter.fromRouterWithComponents(Server.scala:315)
[info]   at play.core.server.ServerFromRouter.fromRouterWithComponents$(Server.scala:312)
[info]   at play.core.server.NettyServer$.fromRouterWithComponents(NettyServer.scala:361)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: io.netty.channel.unix.UnixChannelOption
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at play.core.server.NettyServer.initializeChannelOptionsStaticMembers(NettyServer.scala:314)
[info]   at play.core.server.NettyServer.<init>(NettyServer.scala:63)
[info]   at play.core.server.NettyServerComponents.server(NettyServer.scala:405)
[info]   at play.core.server.NettyServerComponents.server$(NettyServer.scala:401)
[info]   at play.core.server.NettyServer$$anon$1.server$lzycompute(NettyServer.scala:390)
[info]   at play.core.server.NettyServer$$anon$1.server(NettyServer.scala:390)
[info]   at play.core.server.NettyServer$.createServerFromRouter(NettyServer.scala:390)
[info]   ...
```

* Work around SBT bug #4609

* Upgrade `scalatestplus-play` to version 4.0.3

* Upgrade SBT to version 1.2.8